// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/game/data/models/level_entities.dart';
import 'features/home/data/models/settings_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6737881662176777642),
    name: 'DiscoveredWord',
    lastPropertyId: const obx_int.IdUid(4, 1249930117489236603),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 497281602257149343),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7884863597395365360),
        name: 'word',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3722541093043907765),
        name: 'discoveredAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1249930117489236603),
        name: 'levelFound',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3686593575491827498),
    name: 'LevelProgress',
    lastPropertyId: const obx_int.IdUid(5, 5914998075446993962),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3429191490129961572),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4353586362868588055),
        name: 'levelNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3835707696704363861),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2348384882142529901),
        name: 'starsEarned',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5914998075446993962),
        name: 'completedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1936075898955946402),
    name: 'AppSettings',
    lastPropertyId: const obx_int.IdUid(3, 5098069169717731456),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7425299146584243240),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4671417179248478993),
        name: 'isDarkMode',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5098069169717731456),
        name: 'isSoundEnabled',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1936075898955946402),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DiscoveredWord: obx_int.EntityDefinition<DiscoveredWord>(
      model: _entities[0],
      toOneRelations: (DiscoveredWord object) => [],
      toManyRelations: (DiscoveredWord object) => {},
      getId: (DiscoveredWord object) => object.id,
      setId: (DiscoveredWord object, int id) {
        object.id = id;
      },
      objectToFB: (DiscoveredWord object, fb.Builder fbb) {
        final wordOffset = fbb.writeString(object.word);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, wordOffset);
        fbb.addInt64(2, object.discoveredAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.levelFound);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final wordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final discoveredAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final levelFoundParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = DiscoveredWord(
          word: wordParam,
          discoveredAt: discoveredAtParam,
          levelFound: levelFoundParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    LevelProgress: obx_int.EntityDefinition<LevelProgress>(
      model: _entities[1],
      toOneRelations: (LevelProgress object) => [],
      toManyRelations: (LevelProgress object) => {},
      getId: (LevelProgress object) => object.id,
      setId: (LevelProgress object, int id) {
        object.id = id;
      },
      objectToFB: (LevelProgress object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.levelNumber);
        fbb.addBool(2, object.isCompleted);
        fbb.addInt64(3, object.starsEarned);
        fbb.addInt64(4, object.completedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final completedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final levelNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final starsEarnedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final completedAtParam = completedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(completedAtValue);
        final object = LevelProgress(
          levelNumber: levelNumberParam,
          isCompleted: isCompletedParam,
          starsEarned: starsEarnedParam,
          completedAt: completedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    AppSettings: obx_int.EntityDefinition<AppSettings>(
      model: _entities[2],
      toOneRelations: (AppSettings object) => [],
      toManyRelations: (AppSettings object) => {},
      getId: (AppSettings object) => object.id,
      setId: (AppSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettings object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.isDarkMode);
        fbb.addBool(2, object.isSoundEnabled);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final isDarkModeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final isSoundEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final object = AppSettings(
          id: idParam,
          isDarkMode: isDarkModeParam,
          isSoundEnabled: isSoundEnabledParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DiscoveredWord] entity fields to define ObjectBox queries.
class DiscoveredWord_ {
  /// See [DiscoveredWord.id].
  static final id = obx.QueryIntegerProperty<DiscoveredWord>(
    _entities[0].properties[0],
  );

  /// See [DiscoveredWord.word].
  static final word = obx.QueryStringProperty<DiscoveredWord>(
    _entities[0].properties[1],
  );

  /// See [DiscoveredWord.discoveredAt].
  static final discoveredAt = obx.QueryDateProperty<DiscoveredWord>(
    _entities[0].properties[2],
  );

  /// See [DiscoveredWord.levelFound].
  static final levelFound = obx.QueryIntegerProperty<DiscoveredWord>(
    _entities[0].properties[3],
  );
}

/// [LevelProgress] entity fields to define ObjectBox queries.
class LevelProgress_ {
  /// See [LevelProgress.id].
  static final id = obx.QueryIntegerProperty<LevelProgress>(
    _entities[1].properties[0],
  );

  /// See [LevelProgress.levelNumber].
  static final levelNumber = obx.QueryIntegerProperty<LevelProgress>(
    _entities[1].properties[1],
  );

  /// See [LevelProgress.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<LevelProgress>(
    _entities[1].properties[2],
  );

  /// See [LevelProgress.starsEarned].
  static final starsEarned = obx.QueryIntegerProperty<LevelProgress>(
    _entities[1].properties[3],
  );

  /// See [LevelProgress.completedAt].
  static final completedAt = obx.QueryDateProperty<LevelProgress>(
    _entities[1].properties[4],
  );
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id = obx.QueryIntegerProperty<AppSettings>(
    _entities[2].properties[0],
  );

  /// See [AppSettings.isDarkMode].
  static final isDarkMode = obx.QueryBooleanProperty<AppSettings>(
    _entities[2].properties[1],
  );

  /// See [AppSettings.isSoundEnabled].
  static final isSoundEnabled = obx.QueryBooleanProperty<AppSettings>(
    _entities[2].properties[2],
  );
}
